# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: solution/proto/messenger.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'solution/proto/messenger.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1esolution/proto/messenger.proto\x12\x08mes_grpc\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"2\n\x12SendMessageRequest\x12\x0e\n\x06\x61uthor\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"C\n\x13SendMessageResponse\x12,\n\x08sendTime\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"Y\n\x0b\x43hatMessage\x12\x0e\n\x06\x61uthor\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12,\n\x08sendTime\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\x9e\x01\n\x0fMessengerServer\x12J\n\x0bSendMessage\x12\x1c.mes_grpc.SendMessageRequest\x1a\x1d.mes_grpc.SendMessageResponse\x12?\n\x0cReadMessages\x12\x16.google.protobuf.Empty\x1a\x15.mes_grpc.ChatMessage0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'solution.proto.messenger_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDMESSAGEREQUEST']._serialized_start=106
  _globals['_SENDMESSAGEREQUEST']._serialized_end=156
  _globals['_SENDMESSAGERESPONSE']._serialized_start=158
  _globals['_SENDMESSAGERESPONSE']._serialized_end=225
  _globals['_CHATMESSAGE']._serialized_start=227
  _globals['_CHATMESSAGE']._serialized_end=316
  _globals['_MESSENGERSERVER']._serialized_start=319
  _globals['_MESSENGERSERVER']._serialized_end=477
# @@protoc_insertion_point(module_scope)
