syntax = "proto3";

package mes_grpc;

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

service MessengerServer {
  rpc SendMessage(SendMessageRequest) returns (SendMessageResponse);
  rpc ReadMessages(google.protobuf.Empty) returns (stream ReadMessagesResponse);
}

message SendMessageRequest {
  string author = 1;
  string text = 2;
}

message SendMessageResponse {
  google.protobuf.Timestamp sendTime = 1;
}

message ReadMessagesResponse {
  string author = 1;
  string text = 2;
  google.protobuf.Timestamp sendTime = 3;
}
